### ISSUE TITLE
Update Sample App to Showcase "Edit" on Review

### ISSUE THREAD

**Issue by Tyler-Keith-Thompson** [wwt/SwiftCurrent#23]
Our Sample app should show just how awesome this library is by adding "edit" functionality to the review screen.

If you edit your Location you might have to also edit some other downstream things, if you just edit your food choices, it might not. We can showcase just how powerful workflow is with that situation.

**Comment by Tyler-Keith-Thompson** [comment]
@wwt/workflow-developers would this be a good thing for me to work on? I could submit a PR over the weekend. I don't want to rob anybody of a learning opportunity, but I could help with some grunt work.

**Comment by morganzellers** [comment]
> @wwt/workflow-developers would this be a good thing for me to work on? I could submit a PR over the weekend. I don't want to rob anybody of a learning opportunity, but I could help with some grunt work.

I think that would be good

**Comment by Richard-Gist** [comment]
I think this was a great idea, but I don't think it should remain in our scope.  I think it would be better if we moved on to SwiftUI instead of working on this.  And who knows, we may want to change the sample app after we implement SwiftUI or DocC.

Instead of closing this issue, I am recommending we put a low priority label on it and remove it from our board and milestone.

**Comment by Tyler-Keith-Thompson** [comment]
Removing this from the milestone because I do not believe it is strictly necessary to achieve a great onboarding experience.

**Comment by Tyler-Keith-Thompson** [comment]
I'm tempted to close this issue. I don't think this request is particularly valid anymore. The SwiftUI example app is quite a bit nicer and perhaps we should change the UIKit example to be similar.
